Repository codebase-berkeley/teacher-portal, pull requests merged in 2018-10, with the labels that each got.

#13 Pie chart
  client/src/components/CircleChart/CircleChart.css
  client/src/components/CircleChart/CircleChart.jsx
  client/src/components/Login/Login.css
  client/src/components/Login/Login.jsx
  client/src/components/Login/blue-2.jpg
  client/src/components/Units/Unitbox.css
  client/src/components/Units/Unitbox.jsx
  client/src/components/Units/Units.css
  client/src/components/Units/Units.jsx
Labels: enhancement

#26 Fixed travis caching error and added eslint for .jsx files too now
  .travis.yml
  client/package-lock.json
  client/package.json
Labels: bug, enhancement

#31 fixed back button on units page
  client/src/components/Units/Units.jsx
Labels: bug

#40 Added server routes for classes and units
  client/package.json
  client/src/components/Dashboard/ClassBox/ClassBox.jsx
  client/src/components/Dashboard/Dashboard.jsx
  client/src/components/Units/Units.jsx
  server/routes/index.js
Labels: enhancement

#44 Fixed links from units to lessons
  client/src/components/Lessons/AddLessonBox/AddLessonBox.jsx
  client/src/components/Units/Unitbox.jsx
Labels: bug

#50 Added back button and correct navlink for lessons
  client/src/components/Lessons/LessonBox/LessonBox.jsx
  client/src/components/Lessons/Lessons.jsx
Labels: bug

#51 Added another back button and fixed styling
  client/src/components/LessonReflection/LessonReflection.jsx
  server/routes/index.js
Labels: bug
